db:
  image: mysql/mysql-server:5.6
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
  expose:
    - 3306
  ports:
    - 3306:3306

glide:
  build: .
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
  links:
    - db
  volumes:
    - .:/glide
    - ~/tmp:/Downloads
  ports:
    - 8080:8080
  expose:
    - 8080
