FROM snc/centos-base:6.8
MAINTAINER vitaliy.chupinin <vitaliy.chupinin@service-now.com>

## make jenkins user ##
ADD ./config_jenkins_user.sh /config_jenkins_user.sh
RUN chmod 755 /config_jenkins_user.sh
RUN /config_jenkins_user.sh

##  configure sshd ##
ADD ./config_sshd.sh /config_sshd.sh
RUN chmod 755 /config_sshd.sh
RUN /config_sshd.sh


## cleanup ##
RUN rm -f /config_jenkins_user.sh
RUN rm -f /config_sshd.sh

EXPOSE 22

VOLUME /qalab

# copy supervisor conf
COPY ./supervisord-sshd.conf /etc/supervisord.conf
#
# # start supervisor
CMD ["/usr/bin/supervisord", "-n"]
    
